### ISSUE TITLE
I am getting error while executing, I also tried changing my python version, still no luck

### ISSUE THREAD

**Issue by suk79sin** [avinetworks/avitools#12]
[root@taskhost avitools]# ./run.sh -c "f5_converter.py -h"
Using Avitools docker image: avinetworks/avitools:18.2.6 with args: -c f5_converter.py -h
  File "/usr/local/bin/f5_converter.py", line 105
    print 'AVI sdk version: %s Controller Version: %s' \
                                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('AVI sdk version: %s Controller Version: %s' \)?

**Comment by smarunich** [comment]
The issue was caused by installing python3 avimigrationutils as part of 18.2.7 build. The fix added to 18.2.8. 18.2.5 is not affected and the command works "./run.sh -c "f5_converter.py -h" -v 18.2.5". In regards if you want to use 18.2.7 avitools container, you can use it in background mode and do "pip3 uninstall avimigrationutils  & pip install avimigrationutils" that will install python2 f5_converter or run the script as "./run.sh -v 18.2.7 -c "python2 /usr/local/bin/f5_converter.py -h"
